- name: ensure wget is present
  apt:
    name: "wget"
    state: present
    update_cache: yes
  become: yes
  
- name: downloading starkiller
  get_url:
    url: '{{ starkiller_url }}'
    dest: '{{ install_dir }}/starkiller'
    mode: '777'
  
- name: making a symlink
  file: 
   src: '{{ install_dir }}/starkiller'
   dest: /usr/bin/starkiller
   state: link
   


